service: tweet-record
runtime: python
env: flex
entrypoint: python main.py

runtime_config:
  python_version: 3.6

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.6
  disk_size_gb: 10

skip_files:
- ^(.*/)?app\.yaml
- ^README\..*
- \.gitignore
- ^\.git/.*
- ^(.*/)?(.*\.swp)
- ^memos/.*
- ^secret\.yaml
- ^(.*/)?.*\.yaml-example$
- ^(.*/)?.*\.json-example$

includes:
- secret.yaml

